import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import authPhoneRouter from "./auth-phone";
import usersRouter from "./users";
import requestsRouter from "./requests";
import responsesRouter from "./responses";
import messagesRouter from "./messages";
import statsRouter from "./stats";
import analyticsRouter from "./analytics";
import inventoryRouter from "./inventory";
import feedbackRouter from "./feedback";
import stripeRouter from "./stripe";
import listingsRouter from "./listings";
import commissionsRouter from "./commissions";
import aiSearchRouter from "./openai/search";
import analyzeImageRouter from "./openai/analyze-image";
import notificationsRouter from "./notifications";
import messagingPrefsRouter from "./messaging-prefs";
import adminRouter from "./admin";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(authPhoneRouter);
router.use(usersRouter);
router.use(requestsRouter);
router.use(responsesRouter);
router.use(messagesRouter);
router.use(statsRouter);
router.use(analyticsRouter);
router.use(inventoryRouter);
router.use(feedbackRouter);
router.use(stripeRouter);
router.use(listingsRouter);
router.use(commissionsRouter);
router.use(aiSearchRouter);
router.use(analyzeImageRouter);
router.use(notificationsRouter);
router.use(messagingPrefsRouter);
router.use(adminRouter);

export default router;
