// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ai-matching/PhotoBrowseSearch.tsx": () => import("../components/mockups/ai-matching/PhotoBrowseSearch.tsx"),
  "./components/mockups/ai-matching/PhotoRequestForm.tsx": () => import("../components/mockups/ai-matching/PhotoRequestForm.tsx"),
  "./components/mockups/ai-matching/SellerNotification.tsx": () => import("../components/mockups/ai-matching/SellerNotification.tsx")
};
